clean:
	cd error && $(MAKE) clean
	cd getLine && $(MAKE) clean
	cd help && $(MAKE) clean
	cd log && $(MAKE) clean
	cd putLine && $(MAKE) clean
	cd solve && $(MAKE) clean
	cd validate && $(MAKE) clean
